Yaswanth/87270/Theme_UI_Enhanchements
vinu-deriv/trading-app pull request #67
Opened 2023-02-09 12:08 UTC by yaswanth-deriv

2023-02-09 12:26 UTC, farrah-deriv commented on src/components/nav.jsx
> +          category="secondrary"
```suggestion
          category="secondary"
```

2023-02-09 12:26 UTC, farrah-deriv commented on src/components/nav.jsx
> +      {/* <span class={classNames(styles["slider"], styles["round"])}/> */}
can we remove this comment?

2023-02-09 12:26 UTC, farrah-deriv commented on src/components/nav.jsx
> +{is_light_theme()?<img src='https://i.ibb.co/7JfqXxB/sunny.png' class={styles.themeLogo}/>:<img src='https://i.ibb.co/FxzBYR9/night.png' class={styles.themeLogo}/>}
can we import the images as svg?

2023-02-10 07:15 UTC, nijil-deriv requested changes
Let's use the icons we already have in deriv-app.

2023-02-10 07:20 UTC, farrah-deriv approved these changes

2023-02-10 07:58 UTC, yaswanth-deriv commented on src/components/nav.jsx
> +{is_light_theme()?<img src='https://i.ibb.co/7JfqXxB/sunny.png' class={styles.themeLogo}/>:<img src='https://i.ibb.co/FxzBYR9/night.png' class={styles.themeLogo}/>}
Done.Thanks

2023-02-10 09:48 UTC, likhith-deriv approved these changes

2023-02-10 10:02 UTC, nijil-deriv approved these changes

2023-02-10 10:02 UTC, merged